services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: thegame
      POSTGRES_USER: thegame
      POSTGRES_PASSWORD: thegame
    ports:
      - "5432:5432"
    volumes:
      - thegame_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - thegame_redis_data:/data

volumes:
  thegame_pg_data:
  thegame_redis_data:
